info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

management:
  server:
    port: '${SCHEMA_SERVER_PORT:8080}'
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, info'
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

server:
  port: '${SCHEMA_SERVER_PORT:8080}'
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: '${SCHEMA_DATASOURCE_URL:jdbc:h2:file:~/backenddb;DB_CLOSE_ON_EXIT=FALSE}'
    username: '${SCHEMA_DATASOURCE_USER:sa}'
    password: '${SCHEMA_DATASOURCE_PASSWORD:}'
    driver-class-name: '${SCHEMA_DATASOURCE_DRIVERCLASSNAME:org.h2.Driver}'
  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
