apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "process-platform"
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    tier: database
