apiVersion: apps/v1
kind: Deployment
metadata:
  name: "engine-tasklist-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "engine-tasklist-service"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "engine-tasklist-service"
    spec:
      containers:
        - image: "miranum-platform/engine-tasklist-service:latest"
          name: "engine-tasklist-service"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
