apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: "process-platform"
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.3
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/keycloak/bin/kc.sh start-dev"
          envFrom:
            - configMapRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/realms/master"
              port: 8080
